# Generated by Django 6.0.8 on 2026-08-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoiPosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
