# Generated by Django 6.0.8 on 2026-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoiPosApp', '0003_alter_product_id_alter_transaction_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
