# Generated by Django 6.0.8 on 2026-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoiPosApp', '0008_transaction_total_amount_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='cut_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cut_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.CharField(default='Transaction-<function random_string at 0x000002BF19F7C250>', editable=False, max_length=100, unique=True),
        ),
    ]
