# Generated by Django 6.0.8 on 2026-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoiPosApp', '0009_remove_transactionitem_cut_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.CharField(default='Transaction-JACUBNZ2', editable=False, max_length=100, unique=True),
        ),
    ]
