# Generated by Django 6.0.8 on 2026-09-07 13:35

import aoiPosApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoiPosApp', '0010_alter_transaction_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.CharField(default=aoiPosApp.models.generate_transaction_id, editable=False, max_length=100, unique=True),
        ),
    ]
