# Generated by Django 6.0.8 on 2026-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoiPosApp', '0011_alter_transaction_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='effective_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
