# Generated by Django 6.0.8 on 2026-09-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoiPosApp', '0012_transaction_effective_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='staff', max_length=70),
        ),
    ]
